### ISSUE TITLE
[BUG] 32位程序和64位程序编译后无法加载问题

### ISSUE THREAD

**Issue by IBinary6** [MiroKaku/ucxxrt#17]
32位程序Debug/Release编译后(空驱动,里面只使用std::string)
类似代码如下:
```
#include "main.h"

#include <string>

VOID DriverUnLoad(PDRIVER_OBJECT driver) {
  UNREFERENCED_PARAMETER(driver);
  KdPrint(("DriverUnload\r\n"));
}

NTSTATUS DriverMain(PDRIVER_OBJECT driver,
                     PUNICODE_STRING driver_self_reg_path)
/*  NTSTATUS DriverEntry(PDRIVER_OBJECT driver,
                     PUNICODE_STRING driver_self_reg_path)*/ {
  UNREFERENCED_PARAMETER(driver_self_reg_path);
  DbgPrint("DriverEntry");
  std::string s1 = "HelloWOrld";
  DbgPrint("%s", s1.c_str());
  driver->DriverUnload = DriverUnLoad;

  return STATUS_SUCCESS;
}
```
无法加载,编译可以通过.但是加载的时候提示找不到程序(127错误).(说明驱动文件不符合) 
64的release遇到过,但是后面用家里的电脑(纯净电脑) 重新安装了Nuget包中的咱们这个库. 64的release可以编译通过了并且可以加载.
但是32的驱动可以编译通过,但是不能加载. 不知道那里的问题.
家里电脑使用的 WDK SDK = 2019 18362
生成的Debug 常见配置如下:
运行库  = MTD
安全检查 = 禁用GS
spectre缓解 = 已禁用
SDL = 否
警告为错误 = 否(Wx)
警告等级 = 4

Target Os version = windows 7 
Target Platform = Desktop
Driver Mode =KMDF
Driver sign = Off

**Comment by IBinary6** [comment]
测试的驱动加载平台上 win7 32位

**Comment by MeeSong** [comment]
The location of the wrong code：
https://github.com/MiroKaku/ucxxrt/blob/40da51640616bccb8dc3f53418b89e1cd406e98b/src/ucrt/internal/per_thread_data.cpp#L125-L127

`PsGetThreadCreateTime` only Win10 or higher.

**Comment by IBinary6** [comment]
请问下,可否支持下win7, win7很需要.

**Comment by IBinary6** [comment]
亦或者是,能否告知下底层这些类似函数位置. 我可以自己改改. 感谢了.

**Comment by IBinary6** [comment]
Win10 32 10240 = 
![图片](https://user-images.githubusercontent.com/49302027/199144977-09571a72-21af-4a14-847c-120fc8b89b04.png)
Win7 32 sp1 =
![图片](https://user-images.githubusercontent.com/49302027/199145964-3602b6f9-6d40-4eb0-9b83-599478f8e754.png)
ETHREAD + 0X200 = CreateTime.

**Comment by MiroKaku** [comment]
Thanks.

**Comment by IBinary6** [comment]
Thank you for providing such a good library. May I ask how I can sponsor you?  Can you susport (Win7 win8.1 )32bit and 64bit?

**Comment by MeeSong** [comment]
已经移除了 PsGetThreadCreateTime ，Win7之后的版本应该是支持的。

**Comment by MiroKaku** [comment]
编译有什么问题？新开一个 issues

**Comment by IBinary6** [comment]
可否给个联系方式. 稍等,我给个新的issues
