### ISSUE TITLE
[BUG] 无法编译库,不知是否是自己配置问题.

### ISSUE THREAD

**Issue by IBinary6** [MiroKaku/ucxxrt#19]
1.WDK版本使用的是 17763.1 vs2017
2.直接Git clone 最新的 ucxxrt
3.打开Vs进行编译. 编译的时候报 找不到 #include <veil/veil.h>
4.随后又找了大佬的另一个 veil项目.然后clone到 ucxxrt里面.
类似结构如下:
1.第一张图.
![图片](https://user-images.githubusercontent.com/49302027/199381362-00a6d793-b3b2-427d-a8c3-c4d704f62f24.png)
2.第二张图
![图片](https://user-images.githubusercontent.com/49302027/199381399-69d95cfe-0682-478b-99ea-e16f4e4dd035.png)
5.进行编译,然后提示找不到.
![图片](https://user-images.githubusercontent.com/49302027/199381438-537d6a0b-a1ed-45a7-8cdd-3191864512e7.png)

期间设置过 编译的库 使用的sdk版本(与上面一致)
而后设置库 生成的 target version plateform = win7/desktop
SDL = 否
警告视为错误 = 否

**Comment by IBinary6** [comment]
veil在clone ucxxrt之后里面是空的,所以我又找了大佬的另一个项目去使用.  其次我也改过VC++目录中的包含目录.
一样会有如上问题. 在C/C++ 选项里里面修改了 附加包含目录 一样也是如上.

**Comment by MiroKaku** [comment]
不支持 VS2017。

**Comment by IBinary6** [comment]
请问支持的版本是多少. 我使用的Vs2019 SDK = 17763 报如下错误
![图片](https://user-images.githubusercontent.com/49302027/199385822-d5420162-fc18-48b2-bd5d-35beddfe7078.png)

**Comment by MiroKaku** [comment]
![image](https://user-images.githubusercontent.com/50670906/199386494-6f52deaa-66ce-43b3-84ce-ffb69c8a993c.png)
不要改 ucxxr t项目设置啊。veil 重新 git pull

**Comment by IBinary6** [comment]
Ok了. 我reset --hard Head一下. 然后veil也clone到文件夹中了.

**Comment by IBinary6** [comment]
嗯嗯不好意思,不支持C++17

**Comment by IBinary6** [comment]
大佬可否更新个3.3版本. 很好用的一个库. 如果需要帮助.我可以帮你逆向各个环境中你需要的值.

**Comment by MiroKaku** [comment]
修完 #18 再 release

**Comment by IBinary6** [comment]
oK 谢谢大佬.
