### ISSUE TITLE
[BUG] Win764 平台无法加载(32位可以加载)

### ISSUE THREAD

**Issue by IBinary6** [MiroKaku/ucxxrt#20]
你好大佬,使用了我们的 ucxxrt 3.03版本.(Nuget) win732下(inter平台) 可以加载了. 但是win7 64不能加载.
win1064 32 都是可以用的.  win8还没试.  还有能否兼容下AMD.  最近写的驱动要兼容常见平台 (AMD Inter) 现在inter 支持win7 32 win1032/64
如果大佬不方便的话,可否告知一下,改往哪方面学习. 我尝试着兼容下AMD. 如果实在不行.只能自己重写 std::string 和 vector了.
我希望咱们的开源库越来越壮大. 正好在做项目.所以使用了此库.如果大佬有心发展的话.我可以把遇到的问题提一下.这样能帮助我们更加完善这个项目.

**Comment by MeeSong** [comment]
麻烦提供有用的详细信息

**Comment by luciouskami** [comment]
ucxxrt只和架构有关系和cpu的牌子没有关系，目前支持x86和arm架构

**Comment by IBinary6** [comment]
> ucxxrt只和架构有关系和cpu的牌子没有关系，目前支持x86和arm架构

但是相同x64驱动. inter可以加载.(32 /64 win10) 而真机 Adm64(win10) 则不能加载. 不过还是谢谢大佬提供的库. 正考虑换成eastl了. 谢谢了.

**Comment by IBinary6** [comment]
目前还不能用于实战,,问题还是有点多. 再次感谢大佬开源项目. 谢谢提供思路. 如果有时间一定抽空学习下实现. 或者有能力的话可以贡献一下自己的力量.

**Comment by IBinary6** [comment]
我道歉,忘了最重要的一件事,真机无法加载是因为我没签名. 我是用了 nuget 3.04的包,编译后可以(签名)可以在Amd64机器上加载.
对不起. 我的问题.
