### ISSUE TITLE
[BUG] 回调函数中设置DriverUnload 蓝屏.

### ISSUE THREAD

**Issue by IBinary6** [MiroKaku/ucxxrt#21]
首先知道问题的所在.
观看ucxxrt代码. 代码如下
![图片](https://user-images.githubusercontent.com/49302027/201035868-9a769fb6-f3f5-4cb3-b658-ce89a3061ccb.png)
需求:
1.首先我不在DriverMain中设置我自己的DriverUnload. 而是想在用户通过CTRL控制码来告诉我.这时候我在设置DriverUnload
但是观看上面代码得知. 当Invoke_main调用之后会保存我们设置的DriverUnload. 并且设置DriverUnload域为__scrt_common_exit.
此时如果我在 Ctrl回调函数中重新设置 DriverUnload域.就会把 __scrt_common_exit给替换掉. 此时如果驱动卸载的时候会直接运行我自己的DriverUnload. 但是就会触发问题. 首先我电脑开了Verifier验证工具. 会报告我的驱动有内存泄露问题. 而标记则是 ucrt. 所以肯定跟ucrt有关.
后面经过自己调试.发现必须设置为 __scrt_common_exit才可以. 里面会将全局变量 __drv_unload进行调用一次.也就是说 __scrt_common_exit 是对我们的DriverUnload的一层封装.  但是现在就有问题了.  除非我在CTRL 回调函数中手动修改 __drv_unload变量.
否则我要设置DriverUnload只能在 DriverMain中进行设置.
![图片](https://user-images.githubusercontent.com/49302027/201036931-415283d3-8c8d-417d-96c0-2f66103c5b25.png)
所以想问下 作者. 可否导出一个接口.实现这个需求.  而不直接动用 __drv_unload变量.   或者说可否导出一下 __drv_unload. 来实现自定义的卸载.

**Comment by luciouskami** [comment]
啊这？你自己换下就好了啊。

**Comment by IBinary6** [comment]
> 啊这？你自己换下就好了啊。
哈哈,可以自己换.但是能健壮一下库不更好..  我写的驱动目前是千万级别的量.所以有啥问题我都提个建议. 更方便去使用对吧. 我希望咱们越来越好.哈哈哈.

**Comment by IBinary6** [comment]
这也好像算特殊情况. 毕竟DriverUnload不是Dispatch一类函数.按理说可以提供接口去设置的. 它是单独的一个域. 如果被设置过了.我们在设置一下的情况下就不太方便了.

**Comment by MiroKaku** [comment]
你自己在外层备份一份不就好了

**Comment by IBinary6** [comment]
需要修改 crt库里面的_drv_unload. DriverMain调用完已经备份了一下了. 必须在DriverMain中设置一下DriverUnload. 这样才能触发外面的 备份. 如果在驱动里面来说.不修改Crt的情况下.没办法备份...  因为要修改的是 _driver_unload这个全局变量.不是备份__scrt...这个回调.

**Comment by luciouskami** [comment]
> 这也好像算特殊情况. 毕竟DriverUnload不是Dispatch一类函数.按理说可以提供接口去设置的. 它是单独的一个域. 如果被设置过了.我们在设置一下的情况下就不太方便

> 需要修改 crt库里面的_drv_unload. DriverMain调用完已经备份了一下了. 必须在DriverMain中设置一下DriverUnload. 这样才能触发外面的 备份. 如果在驱动里面来说.不修改Crt的情况下.没办法备份... 因为要修改的是 _driver_unload这个全局变量.不是备份__scrt...这个回调.

啊这，这个建议你再看下文档

**Comment by IBinary6** [comment]
我在Ctrl回调函数中可以获取到 DriverUnload域.此时经过DriverMain之后 此域已经设置成了 __scrt相关.  我备份也是备份__scrt相关.我的目的是修改__scr里面的 __drv_unload.  __scr还是作为DriverUnload的域. 这样就不会触发Verifier的内存泄漏验证了.

**Comment by IBinary6** [comment]
其实就是 到导出下 _drv_unload 或者提供个接口单独设置这个值就可以. 当然我提个建议. 如果需要可以改下.不行我就自己编译个. 确实在某些情况下需要不让自己的驱动卸载. 在不修改crt的情况下无法修改到_drv_unload域.

**Comment by IBinary6** [comment]
大佬可否加个接口.求 😄

**Comment by MiroKaku** [comment]
你这样写不就好了吗。（另外：正常开发驱动并不会动态替换Unload）

```c
DRIVER_UNLOAD _OldUnload;

VOID DriverUnload(PDRIVER_OBJECT DriverObject){

    // ...

    if (_OldUnload){
        _OldUnload(DriverObject);
    }
}


NTSTATUS DriverDispatch(
  PDEVICE_OBJECT DeviceObject,
  PIRP Irp
)
{

    //...

    _OldUnload = DriverObject->DriverUnload;
    DriverObject->DriverUnload = DriverUnload;
}
```

**Comment by IBinary6** [comment]
我去试试.. 看看能解决问题吗. scrt里面调用的就是DriverUnload. 所以我可能要提供个中转函数进行设置. 如果不行我自己编译一下吧. 谢谢了.
