### ISSUE TITLE
[BUG] 编译问题

### ISSUE THREAD

**Issue by IBinary6** [MiroKaku/ucxxrt#22]
请问下,编译库的时候 可否选择 MT 或者 MTD运行库.
以及设置编译版本为  Win7  target platform = desktop
没编译过内核库, 虽然现在编译通过了.还是想问下作者你们是怎么设置的.

如下图:
![图片](https://user-images.githubusercontent.com/49302027/201078619-2a7d80fd-daf6-4241-83d5-32be0dc9d7ce.png)

**Comment by IBinary6** [comment]
Universal 和 Desktop 你们编译库的时候选择的是哪个.

**Comment by MiroKaku** [comment]
Readme 不是说了，就两步。不要做多余的事情。issues 不要乱加 label
