### ISSUE TITLE
[疑问] 请问如何编译3.05的这个库

### ISSUE THREAD

**Issue by IBinary6** [MiroKaku/ucxxrt#25]
之前编译3.3左右的时候提过这个问题。 但是那个时候编译成功了。 大佬也解答疑惑了。
原链接：https://github.com/MiroKaku/ucxxrt/issues/19
目前我在项目遇到了需要修改库的问题，所以需要自己重新编译一边。并且修改库的某些地方。
我是用的版本是 Vs2019(根据文档要求） WDK SDK版本 = 10.0.19041.0   C++ 语言开启了支持17
下面是报错。
![image](https://user-images.githubusercontent.com/49302027/211133733-27c4f258-48ca-4da4-ba9f-9baf9c3a4c3a.png)

**Comment by IBinary6** [comment]
![image](https://user-images.githubusercontent.com/49302027/211133752-a9861528-75b1-47ca-933d-ece194181848.png)

**Comment by MeeSong** [comment]
把VS2019升级到最新版，MSVC 组件至少 14.29 版本。

**Comment by IBinary6** [comment]
请问如何能编译出32的库。目前我编译32编译不出来。

**Comment by IBinary6** [comment]
我去尝试下。

**Comment by IBinary6** [comment]
我先更新下， 然后WDK版本 可否使用 17763 。 还有 编译的时候库的选项是否是  win7 然后目标系统是 desktop。 目前默认是 UniverSal

**Comment by IBinary6** [comment]
编译的时候我使用的是2022 只能编译出64位。 32位无法编译。 显示不支持。 我现在先升级VS2019 并且组件设置为14.29. 看看能否编译。

**Comment by IBinary6** [comment]
![image](https://user-images.githubusercontent.com/49302027/211135338-86b3336a-ad00-4130-b281-3ae739ad6e38.png)
Vs2019 = 最新版本，SDK Version = 19041 还是报错。

**Comment by IBinary6** [comment]
大佬经过确认确实是 veil太新了。不支持vs2019了。 我回退了三个版本就可以使用vs2019编译了。
![image](https://user-images.githubusercontent.com/49302027/211138364-158914d2-f1ad-4c8e-9159-eb7891a9270a.png)
不过新版本的修复的Bug我可能要找机会加上。 我编译的是3.04版本。 一会试试3.05版本并且使用上面回退的veil试试。
目前使用的是 vs2019+19041编译的。

**Comment by IBinary6** [comment]
大佬已经确认，是加了 System.win32.h这个文件导致的。 不支持vs2019编译。

**Comment by MeeSong** [comment]
你不是按照文档拉的代码吧，ucxxrt 用的 veil 是 [eae3a46](https://github.com/MiroKaku/Veil/commit/eae3a4640cfce17e500778a209d635dc78f0d9d4) 版本的，怎么可能用到新版本。

![image](https://user-images.githubusercontent.com/6848759/211252513-574533cd-e44c-4b95-b7ef-0ceb7207c79d.png)

**Comment by IBinary6** [comment]
是用的你这个,用完之后Clone不下来 Veil.然后我又单独克隆的veil项目. 也算自己坑自己吧,找到问题了.
