### ISSUE TITLE
[BUG] warning LNK4210: .CRT section exists and BSOD

### ISSUE THREAD

**Issue by hanbingxinjie** [MiroKaku/ucxxrt#26]
Rebuild started...
1>------ Rebuild All started: Project: Empty, Configuration: Debug x64 ------
1>
1>  **************************************************
1>  *         Universal C++ RunTime (UCXXRT)         *
1>  **************************************************
1>  
1>  UCXXRT Path      : D:\Documents\Desktop\Empty\packages\ucxxrt.3.0.5\lib\native\
1>  Platform         : x64
1>  Configuration    : Debug
1>  Tools Version    : 14.34.31933
1>  Platform Version : 10.0.22621.0
1>  Kernel Mode      : true
1>Building 'Empty' with toolset 'WindowsKernelModeDriver10.0' and the 'Desktop' target platform.
1>Source.cpp
1>Stdafx.cpp
1>Generating Code...
1>Source.obj : warning LNK4210: .CRT section exists; there may be unhandled static initializers or terminators
1>LINK : error LNK1218: warning treated as error; no output file generated
1>Done building project "Empty.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
========== Elapsed 00:04.199 ==========

**Comment by MiroKaku** [comment]
What is the code to reproduce the problem?

**Comment by IBinary6** [comment]
我遇到过这个问题,现在已经不用ucxxrt库了. 解决这个问题的办法是看看自己有没有在全局状态下 new对象.
例如:
object g_xxx = new objectxx(); 这样是错误的.
因为量多,要过verifier, 所以用库会导致崩溃在库中.排查比较复杂.

**Comment by hanbingxinjie** [comment]
> 我遇到过这个问题,现在已经不用ucxxrt库了. 解决这个问题的办法是看看自己有没有在全局状态下 new对象. 例如: object g_xxx = new objectxx(); 这样是错误的. 因为量多,要过verifier, 所以用库会导致崩溃在库中.排查比较复杂.

thanks

**Comment by MiroKaku** [comment]
> 我遇到过这个问题,现在已经不用ucxxrt库了. 解决这个问题的办法是看看自己有没有在全局状态下 new对象. 例如: object g_xxx = new objectxx(); 这样是错误的. 因为量多,要过verifier, 所以用库会导致崩溃在库中.排查比较复杂.

我用这段测试代码试了下并不会出现你说的问题。
```cpp
#include <ucxxrt.h>
#include <memory>
#include <functional>

static auto TestGlobalNew = new std::function<void()>(
    [] { DbgPrintEx(DPFLTR_IHVDRIVER_ID, DPFLTR_ERROR_LEVEL, __FUNCTION__); });

extern"C" NTSTATUS DriverMain(PDRIVER_OBJECT, PUNICODE_STRING)
{
    (*TestGlobalNew)();
    return STATUS_UNSUCCESSFUL;
}
```

**Comment by IBinary6** [comment]
我遇到过这个问题,已经不用ucxxrt库了. 1.遇到过.不是用ucxxrt用到了,而是减少ucxxrt依赖的时候遇到的. 2.我是在无ucxxrt下的时候遇到的这个问题.不是ucxxrt的问题. 3.提问者提的Bug我遇到过 就是全局变量的时候进行new对象.  object g_xxx = new object();
这个问题跟ucxxrt无关. 我去掉ucxxrt的时候一直报这个,因为ucxxrt会让我们使用 全局new对象. 4.我已经不用ucxxrt了.感谢怎么好的库,实在是因为量太大了. 不敢用,还是改成纯C++ 编写. c with class的语法. 使用ucxxrt的std::string vector等过不了verifier驱动验证. 这个是没办法的.因为低资源开启后,在进行string构造的时候肯定会失败.

**Comment by IBinary6** [comment]
可能是没表达清楚,见谅. 提问者的问题解决办法就是不要再全局进行new对象. 可以去试一下. 具体能否解决这个就要看项目代码了.或者是不是这个问题引起的.  我遇到的时候跟ucxxrt无关.因为我已经卸载了.
