### ISSUE TITLE
xtime 未定义

### ISSUE THREAD

**Issue by 276585877** [MiroKaku/ucxxrt#30]
微软定义
struct _timespec32
{
    __time32_t tv_sec;
    long       tv_nsec;
};

struct _timespec64
{
    __time64_t tv_sec;
    long       tv_nsec;
};

#ifndef _CRT_NO_TIME_T
    struct timespec
    {
        time_t tv_sec;  // Seconds - >= 0
        long   tv_nsec; // Nanoseconds - [0, 999999999]
    };
#endif

**Comment by MiroKaku** [comment]
VS更新后改了定义的问题。建议直接用Nuget包
