### ISSUE TITLE
Can support for the GetExceptionInformation function be added?

### ISSUE THREAD

**Issue by awaqq520** [MiroKaku/ucxxrt#38]
![image](https://github.com/MiroKaku/ucxxrt/assets/74278175/b1c50d13-6fb3-44b2-9828-a2918757a3de)
I can correctly return GetExceptionCode, but calling GetExceptionInformation
C2707 '_exception_info': error context for internal function

**Comment by MiroKaku** [comment]
[`_exception_info()` outside an exception filter.](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c2707?view=msvc-170)
