### ISSUE TITLE
Can't use kernel function

### ISSUE THREAD

**Issue by lwl4613615** [MiroKaku/ucxxrt#4]
![image](https://user-images.githubusercontent.com/40431645/124219303-ad747080-db2e-11eb-8526-c3aef5938a17.png)
#include <ntifs.h>
#include <ucxxrt.h>
EXTERN_C ULONGLONG KeQueryInterruptTime();
EXTERN_C NTSTATUS DriverMain(PDRIVER_OBJECT aDriverObject, PUNICODE_STRING /*aRegistry*/)
{
    aDriverObject->DriverUnload = [](PDRIVER_OBJECT)
    {
       
        return;
    };
    auto speed= KeQueryInterruptTime();
    KdPrintEx((77, 0, "%llx \n", speed));
    return STATUS_SUCCESS;
}

**Comment by MiroKaku** [comment]
1. 在系统头文件之前定义 `#define _KERNEL_MODE __KERNEL_MODE `
2. 不要自己定义 KeQueryInterruptTime，他是个宏，没有实体函数

**Comment by lwl4613615** [comment]
成功了，吊
